# Generated by Django 6.0.5 on 2026-05-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('Cement', 'Cement'), ('Iron Bar', 'Iron Bar'), ('Nails', 'Nails'), ('Roofing Nails (5kg)', 'Roofing Nails (5kg)'), ('Wheelbarrow', 'Wheelbarrow'), ('Wire Mesh', 'Wire Mesh'), ('Barbed Wire', 'Barbed Wire'), ('Iron Sheets', 'Iron Sheets')], max_length=50)),
                ('specification', models.CharField(blank=True, choices=[('CEM II/N', 'CEM II/N'), ('CEM III/N', 'CEM III/N'), ('10mm', '10mm'), ('12mm', '12mm'), ('16mm', '16mm'), ('1 inch', '1 inch'), ('3 inch', '3 inch'), ('4 inch', '4 inch'), ('5 inch', '5 inch'), ('Roofing Nails 5kg', 'Roofing Nails 5kg'), ('Wheelbarrow', 'Wheelbarrow'), ('Wire Mesh', 'Wire Mesh'), ('High Tensile', 'High Tensile'), ('Low Tensile', 'Low Tensile'), ('Gauge 28', 'Gauge 28'), ('Gauge 30', 'Gauge 30'), ('Gauge 32', 'Gauge 32')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Mobile', 'Mobile Money')], max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dupapp.sale')),
            ],
        ),
    ]
