# Generated by Django 6.0.5 on 2026-05-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dupapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='payment',
            new_name='payment_method',
        ),
    ]
