# Generated by Django 6.0.5 on 2026-05-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dupapp', '0003_supplier_stock_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='distance_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
