# Generated by Django 6.0.5 on 2026-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dupapp', '0005_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='nin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
