# Generated by Django 6.0.5 on 2026-06-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dupapp', '0006_sale_nin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('item_name', 'specification')},
        ),
    ]
