# Generated by Django 6.0.5 on 2026-06-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dupapp', '0007_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
